package calculoseguro;


import calculoseguro.OutroCondutor;
import calculoseguro.Dependentes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Weslley
 */
public class Residentes extends javax.swing.JFrame {

    /**
     * Creates new form Residentes
     */
    public Residentes() {
        initComponents();
        Sim1.setVisible(false);
        Nao1.setVisible(false);
        SexoText.setVisible(false);
        Masculino.setVisible(false);
        Feminino.setVisible(false);
        IdadeText.setVisible(false);
        Idade2.setVisible(false);
        Idade1.setVisible(false);
        jLabel5.setVisible(false);
        jRadioButton3.setVisible(false);
        Feminino1.setVisible(false);
        jLabel6.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jLabel7.setVisible(false);
        jRadioButton3.setVisible(false);
        Feminino2.setVisible(false);
        AlgumMaior.setVisible(false);
        jRadioButton5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Sim1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Nao1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        SexoText = new javax.swing.JLabel();
        Feminino = new javax.swing.JRadioButton();
        Masculino = new javax.swing.JRadioButton();
        IdadeText = new javax.swing.JLabel();
        Idade2 = new javax.swing.JRadioButton();
        Idade1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        Feminino1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Feminino2 = new javax.swing.JRadioButton();
        AlgumMaior = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Possui residentes entre 17 e 25 anos?");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Sim1.setText("Sim");
        Sim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sim1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("                                   Residentes");

        Nao1.setText("Não");
        Nao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nao1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim - Mas não conduzem o veículo", "Sim - Maiores de 18 e conduzem o veículo até 1 dia/semana", "Sim - E o mais velho possui 17 anos", "Não" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        SexoText.setText("Sexo do residente mais novo:");

        Feminino.setText("Feminino");
        Feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemininoActionPerformed(evt);
            }
        });

        Masculino.setText("Maculino");
        Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasculinoActionPerformed(evt);
            }
        });

        IdadeText.setText("Idade do mais novo:");

        Idade2.setText("22 a 25");
        Idade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Idade2ActionPerformed(evt);
            }
        });

        Idade1.setText("17 a 21");
        Idade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Idade1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Sexo do residente mais novo:");

        jRadioButton3.setText("Maculino");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        Feminino1.setText("Feminino");
        Feminino1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Feminino1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Idade do mais novo:");

        jTextField3.setText("17 a 21");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setText("22 a 25");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Sexo do residente mais novo:");

        Feminino2.setText("Feminino");
        Feminino2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Feminino2ActionPerformed(evt);
            }
        });

        AlgumMaior.setText("Algum (Maior de 18 anos) é proprietário?");

        jRadioButton5.setText("Maculino");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SexoText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IdadeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AlgumMaior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton3)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Masculino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                        .addComponent(Sim1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Idade1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                    .addGap(2, 2, 2)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Feminino2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Feminino1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Idade2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Feminino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Nao1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlgumMaior)
                    .addComponent(Sim1)
                    .addComponent(Nao1))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SexoText)
                    .addComponent(Masculino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Feminino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdadeText)
                    .addComponent(Idade1)
                    .addComponent(Idade2))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton5)
                    .addComponent(Feminino1))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jRadioButton3)
                    .addComponent(Feminino2))
                .addGap(18, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Dependentes().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new OutroCondutor().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Sim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sim1ActionPerformed
        Nao1.setSelected(false);
        Sim1.setSelected(true);
    }//GEN-LAST:event_Sim1ActionPerformed

    private void Nao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nao1ActionPerformed
        Sim1.setSelected(false);
        Nao1.setSelected(true);
    }//GEN-LAST:event_Nao1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Object selected = jComboBox1.getSelectedItem();
        if (selected.toString().equals("Sim - Mas não conduzem o veículo")) {
            Feminino.setVisible(true);
            Masculino.setVisible(true);
            SexoText.setVisible(true);
            IdadeText.setVisible(true);
            Idade2.setVisible(true);
            Idade1.setVisible(true);
            jLabel5.setVisible(false);
            jRadioButton3.setVisible(false);
            Feminino1.setVisible(false);
            jRadioButton5.setVisible(false);
            jLabel6.setVisible(false);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jLabel7.setVisible(false);
            jRadioButton3.setVisible(false);
            Feminino2.setVisible(false);
            AlgumMaior.setVisible(false);
            Sim1.setVisible(false);
            Nao1.setVisible(false);;
        } else if (selected.toString().equals("Sim - Maiores de 18 e conduzem o veículo até 1 dia/semana")) {
            Feminino.setVisible(false);
            Masculino.setVisible(false);
            SexoText.setVisible(false);
            IdadeText.setVisible(false);
            Idade2.setVisible(false);
            Idade1.setVisible(false);
            jLabel5.setVisible(true);
            jRadioButton3.setVisible(true);
            Feminino1.setVisible(true);
            jRadioButton5.setVisible(true);
            jLabel6.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jLabel7.setVisible(false);
            jRadioButton3.setVisible(false);
            Feminino2.setVisible(false);
            AlgumMaior.setVisible(true);
            Sim1.setVisible(true);
            Nao1.setVisible(true);
        } else if (selected.toString().equals("Sim - E o mais velho possui 17 anos")) {
            Feminino.setVisible(false);
            Masculino.setVisible(false);
            SexoText.setVisible(false);
            IdadeText.setVisible(false);
            Idade2.setVisible(false);
            Idade1.setVisible(false);
            jLabel5.setVisible(false);
            jRadioButton3.setVisible(false);
            Feminino1.setVisible(false);
            jRadioButton5.setVisible(false);
            jLabel6.setVisible(false);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jLabel7.setVisible(true);
            jRadioButton3.setVisible(true);
            Feminino2.setVisible(true);
            AlgumMaior.setVisible(false);
            Sim1.setVisible(false);
            Nao1.setVisible(false);
        } else {
            Feminino.setVisible(false);
            Masculino.setVisible(false);
            SexoText.setVisible(false);
            IdadeText.setVisible(false);
            Idade2.setVisible(false);
            Idade1.setVisible(false);
            jLabel5.setVisible(false);
            jRadioButton3.setVisible(false);
            Feminino1.setVisible(false);
            jLabel6.setVisible(false);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jLabel7.setVisible(false);
            jRadioButton3.setVisible(false);
            Feminino2.setVisible(false);
            AlgumMaior.setVisible(false);
            Sim1.setVisible(false);
            Nao1.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void FemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemininoActionPerformed
        Masculino.setSelected(false);
        Feminino.setSelected(true);
    }//GEN-LAST:event_FemininoActionPerformed

    private void MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasculinoActionPerformed
        Feminino.setSelected(false);
        Masculino.setSelected(true);
    }//GEN-LAST:event_MasculinoActionPerformed

    private void Idade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Idade1ActionPerformed
        Idade1.setSelected(true);
        Idade2.setSelected(false);
    }//GEN-LAST:event_Idade1ActionPerformed

    private void Idade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Idade2ActionPerformed
        Idade1.setSelected(false);
        Idade2.setSelected(true);
    }//GEN-LAST:event_Idade2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        jRadioButton3.setSelected(true);
        Feminino2.setSelected(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void Feminino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Feminino1ActionPerformed
        jRadioButton5.setSelected(false);
        Feminino1.setSelected(true);
    }//GEN-LAST:event_Feminino1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        jTextField4.setSelected(false);
        jTextField3.setSelected(true);
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        jTextField4.setSelected(true);
        jTextField3.setSelected(false);
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void Feminino2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Feminino2ActionPerformed
        jRadioButton3.setSelected(false);
        Feminino2.setSelected(true);
    }//GEN-LAST:event_Feminino2ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        jRadioButton5.setSelected(true);
        Feminino1.setSelected(false);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Residentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Residentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Residentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Residentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Residentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlgumMaior;
    private javax.swing.JRadioButton Feminino;
    private javax.swing.JRadioButton Feminino1;
    private javax.swing.JRadioButton Feminino2;
    private javax.swing.JRadioButton Idade1;
    private javax.swing.JRadioButton Idade2;
    private javax.swing.JLabel IdadeText;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.JRadioButton Nao1;
    private javax.swing.JLabel SexoText;
    private javax.swing.JRadioButton Sim1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jTextField3;
    private javax.swing.JRadioButton jTextField4;
    // End of variables declaration//GEN-END:variables
}
